manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: Dist16384
      url-base: https://github.com/Dist16384
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: 16d3f3f50436d655486791d1e67041a99f116641
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: Dist16384
      revision: v1.0.0
  self:
    path: config
